# Generated by Django 4.1.1 on 2022-09-30 12:47

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scrapper', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Page_Data',
        ),
    ]
